In [1]:
# Test permutation of the models
from ml2_meta_causal_discovery.models.causaltransformernp import (
    CausalProbabilisticDecoder,
)
from pathlib import Path


work_dir = Path(
    "/vol/bitbucket/ad6013/Research/CausalStructureNeuralProcess/ml2_meta_causal_discovery"
)
model_dir = work_dir / "experiments" / "causal_classification" / "models" / "probabilistic_neuralnet_20var_ERL20U60_NH8_NE4_ND4_DM512_DF1024"
config_file = model_dir / "config.json"

In [2]:
import json
import torch as th


with open(config_file, "r") as f:
    config = json.load(f)

config['num_nodes'] = 2

model = CausalProbabilisticDecoder(**config)

Using 2 decoder layers.


In [3]:
model.load_state_dict(th.load(model_dir / "model_1.pt"))
model = model.eval().to("cuda")

/tmp/ipykernel_3609351/3070766774.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(th.load(model_dir / "model_1.pt"))


In [4]:
x = th.randn(1, 500, 1).to("cuda")
y = 2 * (x ** 3) + th.randn(1, 500, 1).to("cuda")
data = th.cat([x, y], dim=-1)
data = (data - data.mean(dim=1, keepdim=True)) / data.std(dim=1, keepdim=True)

In [5]:
samples = model.sample(data, 50)

tensor([[[-2.4301, -4.8603],
         [-2.1968, -4.3935]]], device='cuda:0', grad_fn=<MulBackward0>)


In [6]:
data = th.cat([y, x], dim=-1)
data = (data - data.mean(dim=1, keepdim=True)) / data.std(dim=1, keepdim=True)

In [7]:
samples = model.sample(data, 50)

tensor([[[-2.1968, -4.3935],
         [-2.4301, -4.8603]]], device='cuda:0', grad_fn=<MulBackward0>)


In [8]:
samples

tensor([[[[0., 0.],
          [1., 0.]]],


        [[[0., 0.],
          [1., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 1.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [1., 0.]]],


        [[[0., 0.],
          [1., 0.]]],


        [[[0., 0.],
          [1., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 1.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]],


        [[[0., 1.],
          [0